environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x" # currently 3.6.6
      PYTHON_ARCH: "64"

install:
  - "SET PYTHONPATH=%PYTHONPATH%;%CD%"
  - "%PYTHON%\\python.exe -m pip install -r tests/requirements.txt"

build: off

test_script:
  - "echo %PYTHONPATH%"
  - "%PYTHON%\\python.exe -m coverage run tests/Analyzer_test.py"
  - "%PYTHON%\\python.exe -m coverage xml"

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"